org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en -Dnet.minecraftforge.gradle.check.certs=false -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1079

minecraft_version=1.20.1
supported_version=1.20.1

archives_base_name=PinTooltips
mod_version=1.3.1-fork
release_type=release
mod_id=pin_tooltips
mod_name=Pin Tooltips
mod_description=Adds the ability to pin tooltips to the screen and view more information from them such as enchantment and mob effect descriptions.